/* mpm.idl: MiKTeX package manager

   Copyright (C) 2006-2007 Christian Schenk

   This file is part of MiKTeX Package Manager.

   MiKTeX Package Manager is free software; you can redistribute it
   and/or modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2, or
   (at your option) any later version.
   
   MiKTeX Package Manager is distributed in the hope that it will be
   useful, but WITHOUT ANY WARRANTY; without even the implied warranty
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with MiKTeX Package Manager; if not, write to the Free
   Software Foundation, 59 Temple Place - Suite 330, Boston, MA
   02111-1307, USA. */

import "oaidl.idl";
import "ocidl.idl";

import "miktexidl.idl";

/* _________________________________________________________________________
   
   MD5
   _________________________________________________________________________ */

typedef [uuid(F92D6E8F-22CC-4585-8309-58440C5A0DFB)] struct MD5
{
  BYTE bits[16];
} MD5;


/* _________________________________________________________________________
   
   PackageInfo
   _________________________________________________________________________ */

typedef [uuid(22A5E6E6-04B3-4540-A122-6A612210F52E)] struct PackageInfo
{
  BSTR deploymentName;
  BSTR displayName;
  BSTR title;
  BSTR version;
  BSTR description;
  BSTR creator;
  DOUBLE sizeRunFiles;
  DOUBLE sizeDocFiles;
  DOUBLE sizeSourceFiles;
  LONG numRunFiles;
  LONG numDocFiles;
  LONG numSourceFiles;
  DATE timePackaged;
  DATE timeInstalled;
  LONG archiveFileSize;
  MD5 digest;
} PackageInfo;

/* _________________________________________________________________________
   
   IPackageInstallerCallback
   _________________________________________________________________________ */

[
  object,
  uuid(4B081787-2C08-4AFD-80E1-B4B3E23324B4),
  nonextensible,
  helpstring("IPackageInstallerCallback Interface"),
  pointer_default(unique)
]
interface IPackageInstallerCallback : IUnknown
{
  [
    helpstring("method ReportLine")
  ]
  HRESULT ReportLine ([in] BSTR line);

  [
    helpstring("method OnRetryableError")
  ]
  HRESULT
  OnRetryableError ([in] BSTR			message,
		    [out,retval] VARIANT_BOOL * doContinue);

  [
    helpstring("method OnProgress")
  ]
  HRESULT
  OnProgress ([in] LONG nf, [out,retval] VARIANT_BOOL * doContinue);
};

/* _________________________________________________________________________
   
   IPackageInstaller
   _________________________________________________________________________ */

[
  object,
  uuid(74C7EE83-4851-4766-B471-9CF29E7C2DA3),
  dual,
  nonextensible,
  helpstring("IPackageInstaller Interface"),
  pointer_default(unique)
]
interface IPackageInstaller : IDispatch
{
  [
    id(1),
    helpstring("method Add")
  ]
  HRESULT
  Add ([in] BSTR packageName, [in] VARIANT_BOOL toBeInstalled);

  [
    id(2),
    helpstring("method SetCallback")
  ]
  HRESULT
  SetCallback ([in] IUnknown * callback);

  [
    id(3),
    helpstring("method InstallRemove")
  ]
  HRESULT
  InstallRemove ();

  [
    id(4),
    helpstring("method GetLastError")
  ]
  HRESULT
  GetErrorInfo ([out,retval] ErrorInfo * errorInfo);

  [
    id(5),
    helpstring("method UpdateDb")
  ]
  HRESULT
  UpdateDb ();
};

/* _________________________________________________________________________
   
   IPackageManager
   _________________________________________________________________________ */

[
  object,
  uuid(C6A0E0A9-532D-46DF-8969-0E0A17539FC9),
  dual,
  nonextensible,
  helpstring("IPackageManager Interface"),
  pointer_default(unique)
]
interface IPackageManager : IDispatch
{
  [
    id(1),
    helpstring("method CreateInstaller")
  ]
  HRESULT
  CreateInstaller ([out,retval] IPackageInstaller ** iInstaller);

  [
    id(2),
    helpstring("method GetPackageInfo")
  ]
  HRESULT
  GetPackageInfo ([in] BSTR			deploymentName,
		  [out,retval] PackageInfo *	packageInfo);
};

/* _________________________________________________________________________
   
   MiKTeXPackageManager
   _________________________________________________________________________ */

[
  uuid(42542DAE-9AAF-41A0-A2FC-7F3CEEA9A5CB),
  version(1.0),
  helpstring("MiKTeX Package Manager 1.0 Type Library")
]
library MiKTeXPackageManagerLib
{
  importlib("stdole2.tlb");

  [
    uuid(E4EC6D80-9E3A-47B7-ADA7-C0621C298527),
    helpstring("MiKTeX Package Manager")
  ]
  coclass PackageManager
  {
    [default] interface IPackageManager;
  };

  interface IPackageInstaller;
  interface IPackageInstallerCallback;
};
