//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by yap.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDD_ADVANCED_OPTIONS            101
#define IDD_DISPLAY                     103
#define IDD_DVIPS                       104
#define IDD_GOTOPAGE                    106
#define IDD_INVERSE_SEARCH              108
#define IDD_MAGNIFYING_GLASS            111
#define IDD_PRINTER                     113
#define IDD_PROGRESS_INDICATOR          114
#define IDD_SECURITY                    115
#define IDD_SOURCE_SPECIALS             116
#define IDD_USER_INTERFACE              117
#define IDD_DOC_PROP_GENERAL            118
#define IDD_DOC_PROP_FONTS              119
#define IDD_ADD_EDITOR                  120
#define IDP_FILE_ASSOCIATION            131
#define IDS_PS_DISABLED                 132
#define IDR_CONTEXT_MENU                138
#define IDR_DVITYPE                     139
#define IDR_FULLSCREEN                  140
#define IDR_MAINFRAME                   141
#define IDP_CHOOSE_EDITOR               143
#define ID_VIEW_TRACE                   154
#define ID_FILE_DOCUMENT_PROPERTIES     155
#define IDR_POINT_MENU                  157
#define IDC_CHECK_ASSOCIATION           203
#define IDC_CLOSE                       205
#define IDC_COMBO_DISPLAY_MODE          206
#define IDC_COMBO_DISPLAY_SHRINK_FACTOR 209
#define IDC_LISTBOX_EDITOR              210
#define IDC_COMBO_PAGENO                212
#define IDC_COMBO_PRINTER_MODE          213
#define IDC_ALL_PAGES                   215
#define IDC_CURRENT_PAGE                216
#define IDC_PAGE_RANGE                  217
#define IDC_EVEN_ODD_PAGES              218
#define IDC_EVEN_PAGES                  219
#define IDC_FIRST_PAGE                  220
#define IDC_LAST_PAGE                   221
#define IDC_ODD_PAGES                   222
#define IDC_EDIT2                       226
#define IDC_EDIT3                       227
#define IDC_ARGUMENTS                   228
#define IDC_EDIT_SOURCE                 232
#define IDC_GOTO                        238
#define IDC_HAND_POINT                  239
#define IDC_HAND_TOOL                   240
#define IDC_HIDE_CURSOR                 241
#define IDC_MAG                         254
#define IDC_MAGGLASS_LARGE_HEIGHT       255
#define IDC_MAGGLASS_LARGE_SHRINK_FACTOR 256
#define IDC_MAGGLASS_LARGE_WIDTH        257
#define IDC_MAGGLASS_MEDIUM_HEIGHT      258
#define IDC_MAGGLASS_MEDIUM_SHRINK_FACTOR 259
#define IDC_MAGGLASS_MEDIUM_WIDTH       260
#define IDC_MAGGLASS_SMALL_HEIGHT       261
#define IDC_MAGGLASS_SMALL_SHRINK_FACTOR 262
#define IDC_MAGGLASS_SMALL_WIDTH        263
#define IDC_MAINTAIN_HORZ_POS           264
#define IDC_MAINTAIN_VERT_POS           265
#define IDC_PRESSED_HAND                267
#define IDC_PROGRESS1                   268
#define IDC_SECURITY_ASK_USER           269
#define IDC_SECURITY_DISABLE_COMMANDS   270
#define IDC_SECURITY_EDIT_SECURE_COMMANDS 271
#define IDC_SECURITY_ENABLE_ALL_COMMANDS 272
#define IDC_SECURITY_SECURE_COMMANDS    273
#define IDC_SHOW_SOURCE_SPECIALS        274
#define IDC_SOURCE_SPECIALS             275
#define IDC_STATIC_RESOLUTION           276
#define IDC_COMBO_PRINTER_NAME          277
#define IDC_EDIT_FILE                   290
#define IDC_EDIT_COMMENT                291
#define IDC_LIST                        291
#define IDC_EDIT_CREATED                292
#define IDC_THE_NAME_OF_THE_GAME        292
#define IDC_EDIT_MODIFIED               293
#define IDC_PATH                        293
#define IDC_COMMAND_LINE                293
#define IDC_EDIT_SIZE                   294
#define IDC_BROWSE                      294
#define IDC_EDIT_NUM_PAGES              295
#define IDC_ADD                         296
#define IDC_DELETE                      297
#define IDC_CHANGE                      298
#define IDC_NAME                        301
#define IDC_COMBO_PAGE_MODE             302
#define ID_REGISTER_MIKTEX              305
#define IDC_COMBO_UNIT                  306
#define IDC_COMBO_OPACITY               309
#define ID_BACK                         44000
#define ID_CANCEL                       44001
#define ID_DARKER_TEXT                  44003
#define ID_DOCUMENT_DOWN                44004
#define ID_DOUBLE_PAGE                  44005
#define ID_END                          44006
#define ID_FILE_DVIPS                   44007
#define ID_FIRST_PAGE                   44008
#define ID_FORWARD                      44009
#define ID_FULLSCREEN                   44010
#define ID_GOTO_PAGE                    44011
#define ID_HELP_KEYBOARD                44012
#define ID_HOME                         44014
#define ID_INDICATOR_COMMAND_PREFIX     44015
#define ID_INDICATOR_PAGE_M_OF_N        44016
#define ID_INDICATOR_POINT              44017
#define ID_INDICATOR_SOURCE             44018
#define ID_LAST_PAGE                    44019
#define ID_LIGHT_TEXT                   44020
#define ID_LIGHTER_TEXT                 44021
#define ID_NEXT_PAGE                    44022
#define ID_PAGE_EDITOR                  44023
#define ID_PREV_PAGE                    44024
#define ID_SB_LINEDOWN                  44025
#define ID_SB_LINELEFT                  44026
#define ID_SB_LINERIGHT                 44027
#define ID_SB_LINEUP                    44028
#define ID_SB_PAGEDOWN                  44029
#define ID_SB_PAGELEFT                  44030
#define ID_SB_PAGERIGHT                 44031
#define ID_SB_PAGEUP                    44032
#define ID_SINGLE_PAGE                  44033
#define ID_TOOLS_ARROW                  44034
#define ID_TOOLS_HAND                   44035
#define ID_TOOLS_MAGNIFYING_GLASS       44036
#define ID_TOOLS_SOURCESPECIALS         44037
#define ID_VIEW_FULLSCREEN              44038
#define ID_VIEW_OPTIONS                 44039
#define ID_VIEW_REFRESH                 44040
#define ID_ZOOM_IN                      44042
#define ID_ZOOM_OUT                     44043
#define ID_CONTINUOUS_SINGLE            44045
#define ID_CONTINUOUS_DOUBLE            44046
#define ID_FILE_SAVEAS                  44048
#define ID_DOCUMENT_UP                  44049
#define ID_PAGEMODE_PK                  44050
#define ID_PAGEMODE_DVIPS               44051
#define ID_VIEW_CENTIMETERS             44068
#define ID_VIEW_INCHES                  44069
#define ID_VIEW_MILLIMETERS             44070
#define ID_VIEW_PICAS                   44071
#define ID_VIEW_POINTS                  44072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         44073
#define _APS_NEXT_CONTROL_VALUE         310
#define _APS_NEXT_SYMED_VALUE           378
#endif
#endif
