//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Setup.rc
//
#define IDR_MANIFEST                    1
#define IDI_SETUP                       1
#define IDS_HEADER_SETTINGS             1
#define IDS_SUBHEADER_SETTINGS          2
#define IDS_INITEXMF                    4
#define IDS_INSTALL_DIR_NOT_EMPTY       5
#define IDS_CANCEL_DOWNLOAD             7
#define IDS_CANCEL_SETUP                8
#define IDS_OPTIONS                     9
#define IDS_LOCAL_GUIDE                 11
#define IDS_LATEX2E_REFERENCE           12
#define IDS_HELP                        13
#define IDS_DVI_VIEWER                  14
#define IDS_FINISH_ERROR                16
#define IDS_REMEDY                      20
#define IDS_RELEASE_NOTES               21
#define IDS_VIEW_LOG_FILE               22
#define IDS_UPDATEWIZ                   24
#define IDS_TIPS                        25
#define IDS_FAQ                         26
#define IDS_HEADER_SHARED               27
#define IDS_SUBHEADER_SHARED            28
#define IDS_SETUPWIZ                    29
#define IDS_HEADER_INSTALLDIR           30
#define IDS_SUBHEADER_INSTALLDIR        31
#define IDS_HEADER_FOLDER               32
#define IDS_SUBHEADER_FOLDER            33
#define IDS_HEADER_ADDTREES             36
#define IDS_SUBHEADER_ADDTREES          37
#define IDS_HEADER_EDITTREES            38
#define IDS_SUBHEADER_EDITTREES         39
#define IDS_HEADER_INFOLIST             40
#define IDS_SUBHEADER_INFOLIST          41
#define IDS_HEADER_FILECOPY             42
#define IDS_SUBHEADER_FILECOPY          43
#define IDS_HEADER_TASK                 52
#define IDS_SUBHEADER_TASK              53
#define IDS_HEADER_LOCAL_REPOSITORY     54
#define IDS_SUBHEADER_LOCAL_REPOSITORY  55
#define IDS_HEADER_PACKAGE_SET          59
#define IDS_SUBHEADER_PACKAGE_SET       60
#define IDS_HEADER_REMOTE_REPOSITORY    61
#define IDS_SUBHEADER_REMOTE_REPOSITORY 62
#define IDS_MPM                         63
#define IDP_NOT_LOCAL_REPOSITORY        66
#define IDS_DOWNLOAD_COMPLETE           67
#define IDS_PROJECT_PAGE                68
#define IDS_MIKTEX_ON_THE_WEB           69
#define IDS_KNOWN_ISSUES                70
#define IDS_REGISTRATION                71
#define IDS_BROWSE_LOCAL                72
#define IDS_HEADER_LICENSE              73
#define IDS_SUBHEADER_LICENSE           74
#define IDD_WELCOME                     129
#define IDD_INSTALLDIR                  130
#define IDD_ADD_TEXMFROOTS              133
#define IDD_INFOLIST                    134
#define IDD_FINISH                      135
#define IDD_FOLDER                      136
#define IDD_FILECOPY                    137
#define IDD_SHARED                      141
#define IDD_EDIT_TEXMFROOTS             142
#define IDD_TASK                        143
#define IDB_HEADER                      148
#define IDB_WATERMARK                   149
#define IDA_FILECOPY                    150
#define IDA_DOWNLOAD                    151
#define IDC_BROWSE                      207
#define IDC_FILENAME                    212
#define IDD_LOCAL_REPOSITORY            215
#define IDD_PACKAGE_SET_INSTALL         216
#define IDD_REMOTE_REPOSITORY           217
#define IDD_MD_TASK                     218
#define IDD_LICENSE                     219
#define IDD_PACKAGE_SET_DOWNLOAD        220
#define IDD_SETTINGS                    221
#define IDD_PROXY_AUTHENTICATION        222
#define IDD_CONNECTION_SETTINGS         223
#define IDC_LIST                        1003
#define IDC_WELCOME                     1006
#define IDC_NOADDTEXMF                  1008
#define IDC_USE_PROXY                   1008
#define IDC_ADDTEXMF                    1009
#define IDC_PROGRESS1                   1010
#define IDC_CONNECTION_SETTINGS         1010
#define IDC_PATHNAME                    1011
#define IDC_PROGRESS2                   1011
#define IDC_PROXY_HOST                  1011
#define IDC_PROXY_PORT                  1012
#define IDC_AUTH_REQUIRED               1013
#define IDC_FOLDER                      1015
#define IDC_STATIC_ADDRESS              1016
#define IDC_STATIC_PORT                 1017
#define IDC_INFO                        1019
#define IDC_PROXY_NAME                  1020
#define IDC_PROXY_PASSWORD              1021
#define IDC_PACKAGE                     1022
#define IDC_PROGRESS1_TITLE             1024
#define IDC_PROGRESS2_TITLE             1025
#define IDC_VIEW_RELNOTES               1029
#define IDC_SHARED                      1035
#define IDC_JUST_FOR_ME                 1036
#define IDC_LIST_TEXMFROOTS             1039
#define IDC_ADD                         1040
#define IDC_DELETE                      1041
#define IDC_MOVEUP                      1042
#define IDC_MOVEDOWN                    1043
#define IDC_REPORT                      1043
#define IDC_DOWNLOAD_ONLY               1046
#define IDC_ANI                         1046
#define IDC_MESSAGE                     1047
#define IDC_INSTALL_FROM_LOCAL_REPOSITORY 1047
#define IDC_SMALL                       1048
#define IDC_INSTALL_FROM_REMOTE_REPOSITORY 1049
#define IDC_TOTAL                       1050
#define IDC_ETA                         1052
#define IDC_ETA_TITLE                   1053
#define IDC_STATUS                      1054
#define IDC_PREPARE_MIKTEXDIRECT        1057
#define IDC_INSTALL                     1058
#define IDC_LICENSE                     1062
#define IDC_ACCEPT_LICENSE              1063
#define IDC_TEXMF_ROOT                  1064
#define IDC_COMBO1                      1065
#define IDC_COMBO2                      1066
#define IDC_INSTALL_ON_THE_FLY          1075
#define IDS_SUPPORT                     57345

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
