if(URIPARSER_INCLUDE_DIR)
  set(URIPARSER_FIND_QUIETLY TRUE)
endif(URIPARSER_INCLUDE_DIR)

find_path(URIPARSER_INCLUDE_DIR uriparser/Uri.h)

set(URIPARSER_NAMES uriparser)
find_library(URIPARSER_LIBRARY NAMES ${URIPARSER_NAMES})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(URIPARSER DEFAULT_MSG URIPARSER_LIBRARY URIPARSER_INCLUDE_DIR)

if(URIPARSER_FOUND)
  set(URIPARSER_LIBRARIES ${URIPARSER_LIBRARY})
else(URIPARSER_FOUND)
  set(URIPARSER_LIBRARIES)
endif(URIPARSER_FOUND)

mark_as_advanced(URIPARSER_LIBRARY URIPARSER_INCLUDE_DIR)
