/* repositoryH.h
   Generated by gSOAP 2.7.6e from Repository.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef repositoryH_H
#define repositoryH_H
#include "repositoryStub.h"
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_mws__RepositoryStatus
#define SOAP_TYPE_mws__RepositoryStatus (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mws__RepositoryStatus(struct soap*, enum mws__RepositoryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mws__RepositoryStatus(struct soap*, const enum mws__RepositoryStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mws__RepositoryStatus(struct soap*, const char*, int, const enum mws__RepositoryStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_mws__RepositoryStatus2s(struct soap*, enum mws__RepositoryStatus);
SOAP_FMAC3 enum mws__RepositoryStatus * SOAP_FMAC4 soap_get_mws__RepositoryStatus(struct soap*, enum mws__RepositoryStatus *, const char*, const char*);
SOAP_FMAC3 enum mws__RepositoryStatus * SOAP_FMAC4 soap_in_mws__RepositoryStatus(struct soap*, const char*, enum mws__RepositoryStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2mws__RepositoryStatus(struct soap*, const char*, enum mws__RepositoryStatus *);

#ifndef SOAP_TYPE_mws__Levels
#define SOAP_TYPE_mws__Levels (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mws__Levels(struct soap*, enum mws__Levels *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mws__Levels(struct soap*, const enum mws__Levels *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mws__Levels(struct soap*, const char*, int, const enum mws__Levels *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_mws__Levels2s(struct soap*, enum mws__Levels);
SOAP_FMAC3 enum mws__Levels * SOAP_FMAC4 soap_get_mws__Levels(struct soap*, enum mws__Levels *, const char*, const char*);
SOAP_FMAC3 enum mws__Levels * SOAP_FMAC4 soap_in_mws__Levels(struct soap*, const char*, enum mws__Levels *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2mws__Levels(struct soap*, const char*, enum mws__Levels *);

#ifndef SOAP_TYPE_mws__Integrities
#define SOAP_TYPE_mws__Integrities (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mws__Integrities(struct soap*, enum mws__Integrities *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mws__Integrities(struct soap*, const enum mws__Integrities *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mws__Integrities(struct soap*, const char*, int, const enum mws__Integrities *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_mws__Integrities2s(struct soap*, enum mws__Integrities);
SOAP_FMAC3 enum mws__Integrities * SOAP_FMAC4 soap_get_mws__Integrities(struct soap*, enum mws__Integrities *, const char*, const char*);
SOAP_FMAC3 enum mws__Integrities * SOAP_FMAC4 soap_in_mws__Integrities(struct soap*, const char*, enum mws__Integrities *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2mws__Integrities(struct soap*, const char*, enum mws__Integrities *);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__GetRepositoriesResponse
#define SOAP_TYPE__mws__GetRepositoriesResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__GetRepositoriesResponse(struct soap*, const char*, int, const _mws__GetRepositoriesResponse *, const char*);
SOAP_FMAC3 _mws__GetRepositoriesResponse * SOAP_FMAC4 soap_get__mws__GetRepositoriesResponse(struct soap*, _mws__GetRepositoriesResponse *, const char*, const char*);
SOAP_FMAC3 _mws__GetRepositoriesResponse * SOAP_FMAC4 soap_in__mws__GetRepositoriesResponse(struct soap*, const char*, _mws__GetRepositoriesResponse *, const char*);
SOAP_FMAC5 _mws__GetRepositoriesResponse * SOAP_FMAC6 soap_new__mws__GetRepositoriesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__GetRepositoriesResponse(struct soap*, _mws__GetRepositoriesResponse*);
SOAP_FMAC3 _mws__GetRepositoriesResponse * SOAP_FMAC4 soap_instantiate__mws__GetRepositoriesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__GetRepositoriesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__GetRepositories
#define SOAP_TYPE__mws__GetRepositories (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__GetRepositories(struct soap*, const char*, int, const _mws__GetRepositories *, const char*);
SOAP_FMAC3 _mws__GetRepositories * SOAP_FMAC4 soap_get__mws__GetRepositories(struct soap*, _mws__GetRepositories *, const char*, const char*);
SOAP_FMAC3 _mws__GetRepositories * SOAP_FMAC4 soap_in__mws__GetRepositories(struct soap*, const char*, _mws__GetRepositories *, const char*);
SOAP_FMAC5 _mws__GetRepositories * SOAP_FMAC6 soap_new__mws__GetRepositories(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__GetRepositories(struct soap*, _mws__GetRepositories*);
SOAP_FMAC3 _mws__GetRepositories * SOAP_FMAC4 soap_instantiate__mws__GetRepositories(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__GetRepositories(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__GetAllRepositoriesResponse
#define SOAP_TYPE__mws__GetAllRepositoriesResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__GetAllRepositoriesResponse(struct soap*, const char*, int, const _mws__GetAllRepositoriesResponse *, const char*);
SOAP_FMAC3 _mws__GetAllRepositoriesResponse * SOAP_FMAC4 soap_get__mws__GetAllRepositoriesResponse(struct soap*, _mws__GetAllRepositoriesResponse *, const char*, const char*);
SOAP_FMAC3 _mws__GetAllRepositoriesResponse * SOAP_FMAC4 soap_in__mws__GetAllRepositoriesResponse(struct soap*, const char*, _mws__GetAllRepositoriesResponse *, const char*);
SOAP_FMAC5 _mws__GetAllRepositoriesResponse * SOAP_FMAC6 soap_new__mws__GetAllRepositoriesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__GetAllRepositoriesResponse(struct soap*, _mws__GetAllRepositoriesResponse*);
SOAP_FMAC3 _mws__GetAllRepositoriesResponse * SOAP_FMAC4 soap_instantiate__mws__GetAllRepositoriesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__GetAllRepositoriesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__GetAllRepositories
#define SOAP_TYPE__mws__GetAllRepositories (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__GetAllRepositories(struct soap*, const char*, int, const _mws__GetAllRepositories *, const char*);
SOAP_FMAC3 _mws__GetAllRepositories * SOAP_FMAC4 soap_get__mws__GetAllRepositories(struct soap*, _mws__GetAllRepositories *, const char*, const char*);
SOAP_FMAC3 _mws__GetAllRepositories * SOAP_FMAC4 soap_in__mws__GetAllRepositories(struct soap*, const char*, _mws__GetAllRepositories *, const char*);
SOAP_FMAC5 _mws__GetAllRepositories * SOAP_FMAC6 soap_new__mws__GetAllRepositories(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__GetAllRepositories(struct soap*, _mws__GetAllRepositories*);
SOAP_FMAC3 _mws__GetAllRepositories * SOAP_FMAC4 soap_instantiate__mws__GetAllRepositories(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__GetAllRepositories(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__PickRepositoryResponse
#define SOAP_TYPE__mws__PickRepositoryResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__PickRepositoryResponse(struct soap*, const char*, int, const _mws__PickRepositoryResponse *, const char*);
SOAP_FMAC3 _mws__PickRepositoryResponse * SOAP_FMAC4 soap_get__mws__PickRepositoryResponse(struct soap*, _mws__PickRepositoryResponse *, const char*, const char*);
SOAP_FMAC3 _mws__PickRepositoryResponse * SOAP_FMAC4 soap_in__mws__PickRepositoryResponse(struct soap*, const char*, _mws__PickRepositoryResponse *, const char*);
SOAP_FMAC5 _mws__PickRepositoryResponse * SOAP_FMAC6 soap_new__mws__PickRepositoryResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__PickRepositoryResponse(struct soap*, _mws__PickRepositoryResponse*);
SOAP_FMAC3 _mws__PickRepositoryResponse * SOAP_FMAC4 soap_instantiate__mws__PickRepositoryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__PickRepositoryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__PickRepository
#define SOAP_TYPE__mws__PickRepository (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__PickRepository(struct soap*, const char*, int, const _mws__PickRepository *, const char*);
SOAP_FMAC3 _mws__PickRepository * SOAP_FMAC4 soap_get__mws__PickRepository(struct soap*, _mws__PickRepository *, const char*, const char*);
SOAP_FMAC3 _mws__PickRepository * SOAP_FMAC4 soap_in__mws__PickRepository(struct soap*, const char*, _mws__PickRepository *, const char*);
SOAP_FMAC5 _mws__PickRepository * SOAP_FMAC6 soap_new__mws__PickRepository(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__PickRepository(struct soap*, _mws__PickRepository*);
SOAP_FMAC3 _mws__PickRepository * SOAP_FMAC4 soap_instantiate__mws__PickRepository(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__PickRepository(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__TryGetRepositoryInfoResponse
#define SOAP_TYPE__mws__TryGetRepositoryInfoResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__TryGetRepositoryInfoResponse(struct soap*, const char*, int, const _mws__TryGetRepositoryInfoResponse *, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfoResponse * SOAP_FMAC4 soap_get__mws__TryGetRepositoryInfoResponse(struct soap*, _mws__TryGetRepositoryInfoResponse *, const char*, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfoResponse * SOAP_FMAC4 soap_in__mws__TryGetRepositoryInfoResponse(struct soap*, const char*, _mws__TryGetRepositoryInfoResponse *, const char*);
SOAP_FMAC5 _mws__TryGetRepositoryInfoResponse * SOAP_FMAC6 soap_new__mws__TryGetRepositoryInfoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__TryGetRepositoryInfoResponse(struct soap*, _mws__TryGetRepositoryInfoResponse*);
SOAP_FMAC3 _mws__TryGetRepositoryInfoResponse * SOAP_FMAC4 soap_instantiate__mws__TryGetRepositoryInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__TryGetRepositoryInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__mws__TryGetRepositoryInfo
#define SOAP_TYPE__mws__TryGetRepositoryInfo (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__mws__TryGetRepositoryInfo(struct soap*, const char*, int, const _mws__TryGetRepositoryInfo *, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_get__mws__TryGetRepositoryInfo(struct soap*, _mws__TryGetRepositoryInfo *, const char*, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_in__mws__TryGetRepositoryInfo(struct soap*, const char*, _mws__TryGetRepositoryInfo *, const char*);
SOAP_FMAC5 _mws__TryGetRepositoryInfo * SOAP_FMAC6 soap_new__mws__TryGetRepositoryInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__mws__TryGetRepositoryInfo(struct soap*, _mws__TryGetRepositoryInfo*);
SOAP_FMAC3 _mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_instantiate__mws__TryGetRepositoryInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__mws__TryGetRepositoryInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_mws__ArrayOfRepositoryInfo
#define SOAP_TYPE_mws__ArrayOfRepositoryInfo (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_mws__ArrayOfRepositoryInfo(struct soap*, const char*, int, const mws__ArrayOfRepositoryInfo *, const char*);
SOAP_FMAC3 mws__ArrayOfRepositoryInfo * SOAP_FMAC4 soap_get_mws__ArrayOfRepositoryInfo(struct soap*, mws__ArrayOfRepositoryInfo *, const char*, const char*);
SOAP_FMAC3 mws__ArrayOfRepositoryInfo * SOAP_FMAC4 soap_in_mws__ArrayOfRepositoryInfo(struct soap*, const char*, mws__ArrayOfRepositoryInfo *, const char*);
SOAP_FMAC5 mws__ArrayOfRepositoryInfo * SOAP_FMAC6 soap_new_mws__ArrayOfRepositoryInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_mws__ArrayOfRepositoryInfo(struct soap*, mws__ArrayOfRepositoryInfo*);
SOAP_FMAC3 mws__ArrayOfRepositoryInfo * SOAP_FMAC4 soap_instantiate_mws__ArrayOfRepositoryInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_mws__ArrayOfRepositoryInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_mws__RepositoryInfo
#define SOAP_TYPE_mws__RepositoryInfo (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_mws__RepositoryInfo(struct soap*, const char*, int, const mws__RepositoryInfo *, const char*);
SOAP_FMAC3 mws__RepositoryInfo * SOAP_FMAC4 soap_get_mws__RepositoryInfo(struct soap*, mws__RepositoryInfo *, const char*, const char*);
SOAP_FMAC3 mws__RepositoryInfo * SOAP_FMAC4 soap_in_mws__RepositoryInfo(struct soap*, const char*, mws__RepositoryInfo *, const char*);
SOAP_FMAC5 mws__RepositoryInfo * SOAP_FMAC6 soap_new_mws__RepositoryInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_mws__RepositoryInfo(struct soap*, mws__RepositoryInfo*);
SOAP_FMAC3 mws__RepositoryInfo * SOAP_FMAC4 soap_instantiate_mws__RepositoryInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_mws__RepositoryInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___mws__GetRepositories_
#define SOAP_TYPE___mws__GetRepositories_ (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__GetRepositories_(struct soap*, const struct __mws__GetRepositories_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__GetRepositories_(struct soap*, struct __mws__GetRepositories_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__GetRepositories_(struct soap*, const struct __mws__GetRepositories_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__GetRepositories_(struct soap*, const char*, int, const struct __mws__GetRepositories_ *, const char*);
SOAP_FMAC3 struct __mws__GetRepositories_ * SOAP_FMAC4 soap_get___mws__GetRepositories_(struct soap*, struct __mws__GetRepositories_ *, const char*, const char*);
SOAP_FMAC3 struct __mws__GetRepositories_ * SOAP_FMAC4 soap_in___mws__GetRepositories_(struct soap*, const char*, struct __mws__GetRepositories_ *, const char*);
SOAP_FMAC5 struct __mws__GetRepositories_ * SOAP_FMAC6 soap_new___mws__GetRepositories_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__GetRepositories_(struct soap*, struct __mws__GetRepositories_*);
SOAP_FMAC3 struct __mws__GetRepositories_ * SOAP_FMAC4 soap_instantiate___mws__GetRepositories_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__GetRepositories_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__GetAllRepositories_
#define SOAP_TYPE___mws__GetAllRepositories_ (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__GetAllRepositories_(struct soap*, const struct __mws__GetAllRepositories_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__GetAllRepositories_(struct soap*, struct __mws__GetAllRepositories_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__GetAllRepositories_(struct soap*, const struct __mws__GetAllRepositories_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__GetAllRepositories_(struct soap*, const char*, int, const struct __mws__GetAllRepositories_ *, const char*);
SOAP_FMAC3 struct __mws__GetAllRepositories_ * SOAP_FMAC4 soap_get___mws__GetAllRepositories_(struct soap*, struct __mws__GetAllRepositories_ *, const char*, const char*);
SOAP_FMAC3 struct __mws__GetAllRepositories_ * SOAP_FMAC4 soap_in___mws__GetAllRepositories_(struct soap*, const char*, struct __mws__GetAllRepositories_ *, const char*);
SOAP_FMAC5 struct __mws__GetAllRepositories_ * SOAP_FMAC6 soap_new___mws__GetAllRepositories_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__GetAllRepositories_(struct soap*, struct __mws__GetAllRepositories_*);
SOAP_FMAC3 struct __mws__GetAllRepositories_ * SOAP_FMAC4 soap_instantiate___mws__GetAllRepositories_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__GetAllRepositories_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__PickRepository_
#define SOAP_TYPE___mws__PickRepository_ (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__PickRepository_(struct soap*, const struct __mws__PickRepository_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__PickRepository_(struct soap*, struct __mws__PickRepository_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__PickRepository_(struct soap*, const struct __mws__PickRepository_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__PickRepository_(struct soap*, const char*, int, const struct __mws__PickRepository_ *, const char*);
SOAP_FMAC3 struct __mws__PickRepository_ * SOAP_FMAC4 soap_get___mws__PickRepository_(struct soap*, struct __mws__PickRepository_ *, const char*, const char*);
SOAP_FMAC3 struct __mws__PickRepository_ * SOAP_FMAC4 soap_in___mws__PickRepository_(struct soap*, const char*, struct __mws__PickRepository_ *, const char*);
SOAP_FMAC5 struct __mws__PickRepository_ * SOAP_FMAC6 soap_new___mws__PickRepository_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__PickRepository_(struct soap*, struct __mws__PickRepository_*);
SOAP_FMAC3 struct __mws__PickRepository_ * SOAP_FMAC4 soap_instantiate___mws__PickRepository_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__PickRepository_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__TryGetRepositoryInfo_
#define SOAP_TYPE___mws__TryGetRepositoryInfo_ (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__TryGetRepositoryInfo_(struct soap*, const struct __mws__TryGetRepositoryInfo_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__TryGetRepositoryInfo_(struct soap*, struct __mws__TryGetRepositoryInfo_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__TryGetRepositoryInfo_(struct soap*, const struct __mws__TryGetRepositoryInfo_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__TryGetRepositoryInfo_(struct soap*, const char*, int, const struct __mws__TryGetRepositoryInfo_ *, const char*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo_ * SOAP_FMAC4 soap_get___mws__TryGetRepositoryInfo_(struct soap*, struct __mws__TryGetRepositoryInfo_ *, const char*, const char*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo_ * SOAP_FMAC4 soap_in___mws__TryGetRepositoryInfo_(struct soap*, const char*, struct __mws__TryGetRepositoryInfo_ *, const char*);
SOAP_FMAC5 struct __mws__TryGetRepositoryInfo_ * SOAP_FMAC6 soap_new___mws__TryGetRepositoryInfo_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__TryGetRepositoryInfo_(struct soap*, struct __mws__TryGetRepositoryInfo_*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo_ * SOAP_FMAC4 soap_instantiate___mws__TryGetRepositoryInfo_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__TryGetRepositoryInfo_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__GetRepositories
#define SOAP_TYPE___mws__GetRepositories (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__GetRepositories(struct soap*, const struct __mws__GetRepositories *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__GetRepositories(struct soap*, struct __mws__GetRepositories *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__GetRepositories(struct soap*, const struct __mws__GetRepositories *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__GetRepositories(struct soap*, const char*, int, const struct __mws__GetRepositories *, const char*);
SOAP_FMAC3 struct __mws__GetRepositories * SOAP_FMAC4 soap_get___mws__GetRepositories(struct soap*, struct __mws__GetRepositories *, const char*, const char*);
SOAP_FMAC3 struct __mws__GetRepositories * SOAP_FMAC4 soap_in___mws__GetRepositories(struct soap*, const char*, struct __mws__GetRepositories *, const char*);
SOAP_FMAC5 struct __mws__GetRepositories * SOAP_FMAC6 soap_new___mws__GetRepositories(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__GetRepositories(struct soap*, struct __mws__GetRepositories*);
SOAP_FMAC3 struct __mws__GetRepositories * SOAP_FMAC4 soap_instantiate___mws__GetRepositories(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__GetRepositories(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__GetAllRepositories
#define SOAP_TYPE___mws__GetAllRepositories (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__GetAllRepositories(struct soap*, const struct __mws__GetAllRepositories *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__GetAllRepositories(struct soap*, struct __mws__GetAllRepositories *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__GetAllRepositories(struct soap*, const struct __mws__GetAllRepositories *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__GetAllRepositories(struct soap*, const char*, int, const struct __mws__GetAllRepositories *, const char*);
SOAP_FMAC3 struct __mws__GetAllRepositories * SOAP_FMAC4 soap_get___mws__GetAllRepositories(struct soap*, struct __mws__GetAllRepositories *, const char*, const char*);
SOAP_FMAC3 struct __mws__GetAllRepositories * SOAP_FMAC4 soap_in___mws__GetAllRepositories(struct soap*, const char*, struct __mws__GetAllRepositories *, const char*);
SOAP_FMAC5 struct __mws__GetAllRepositories * SOAP_FMAC6 soap_new___mws__GetAllRepositories(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__GetAllRepositories(struct soap*, struct __mws__GetAllRepositories*);
SOAP_FMAC3 struct __mws__GetAllRepositories * SOAP_FMAC4 soap_instantiate___mws__GetAllRepositories(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__GetAllRepositories(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__PickRepository
#define SOAP_TYPE___mws__PickRepository (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__PickRepository(struct soap*, const struct __mws__PickRepository *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__PickRepository(struct soap*, struct __mws__PickRepository *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__PickRepository(struct soap*, const struct __mws__PickRepository *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__PickRepository(struct soap*, const char*, int, const struct __mws__PickRepository *, const char*);
SOAP_FMAC3 struct __mws__PickRepository * SOAP_FMAC4 soap_get___mws__PickRepository(struct soap*, struct __mws__PickRepository *, const char*, const char*);
SOAP_FMAC3 struct __mws__PickRepository * SOAP_FMAC4 soap_in___mws__PickRepository(struct soap*, const char*, struct __mws__PickRepository *, const char*);
SOAP_FMAC5 struct __mws__PickRepository * SOAP_FMAC6 soap_new___mws__PickRepository(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__PickRepository(struct soap*, struct __mws__PickRepository*);
SOAP_FMAC3 struct __mws__PickRepository * SOAP_FMAC4 soap_instantiate___mws__PickRepository(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__PickRepository(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___mws__TryGetRepositoryInfo
#define SOAP_TYPE___mws__TryGetRepositoryInfo (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___mws__TryGetRepositoryInfo(struct soap*, const struct __mws__TryGetRepositoryInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___mws__TryGetRepositoryInfo(struct soap*, struct __mws__TryGetRepositoryInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___mws__TryGetRepositoryInfo(struct soap*, const struct __mws__TryGetRepositoryInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___mws__TryGetRepositoryInfo(struct soap*, const char*, int, const struct __mws__TryGetRepositoryInfo *, const char*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_get___mws__TryGetRepositoryInfo(struct soap*, struct __mws__TryGetRepositoryInfo *, const char*, const char*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_in___mws__TryGetRepositoryInfo(struct soap*, const char*, struct __mws__TryGetRepositoryInfo *, const char*);
SOAP_FMAC5 struct __mws__TryGetRepositoryInfo * SOAP_FMAC6 soap_new___mws__TryGetRepositoryInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___mws__TryGetRepositoryInfo(struct soap*, struct __mws__TryGetRepositoryInfo*);
SOAP_FMAC3 struct __mws__TryGetRepositoryInfo * SOAP_FMAC4 soap_instantiate___mws__TryGetRepositoryInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___mws__TryGetRepositoryInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_mws__GetRepositoriesResponse
#define SOAP_TYPE_PointerTo_mws__GetRepositoriesResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__GetRepositoriesResponse(struct soap*, _mws__GetRepositoriesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__GetRepositoriesResponse(struct soap*, _mws__GetRepositoriesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__GetRepositoriesResponse(struct soap*, const char *, int, _mws__GetRepositoriesResponse *const*, const char *);
SOAP_FMAC3 _mws__GetRepositoriesResponse ** SOAP_FMAC4 soap_get_PointerTo_mws__GetRepositoriesResponse(struct soap*, _mws__GetRepositoriesResponse **, const char*, const char*);
SOAP_FMAC3 _mws__GetRepositoriesResponse ** SOAP_FMAC4 soap_in_PointerTo_mws__GetRepositoriesResponse(struct soap*, const char*, _mws__GetRepositoriesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__GetRepositories
#define SOAP_TYPE_PointerTo_mws__GetRepositories (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__GetRepositories(struct soap*, _mws__GetRepositories *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__GetRepositories(struct soap*, _mws__GetRepositories *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__GetRepositories(struct soap*, const char *, int, _mws__GetRepositories *const*, const char *);
SOAP_FMAC3 _mws__GetRepositories ** SOAP_FMAC4 soap_get_PointerTo_mws__GetRepositories(struct soap*, _mws__GetRepositories **, const char*, const char*);
SOAP_FMAC3 _mws__GetRepositories ** SOAP_FMAC4 soap_in_PointerTo_mws__GetRepositories(struct soap*, const char*, _mws__GetRepositories **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__GetAllRepositoriesResponse
#define SOAP_TYPE_PointerTo_mws__GetAllRepositoriesResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__GetAllRepositoriesResponse(struct soap*, _mws__GetAllRepositoriesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__GetAllRepositoriesResponse(struct soap*, _mws__GetAllRepositoriesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__GetAllRepositoriesResponse(struct soap*, const char *, int, _mws__GetAllRepositoriesResponse *const*, const char *);
SOAP_FMAC3 _mws__GetAllRepositoriesResponse ** SOAP_FMAC4 soap_get_PointerTo_mws__GetAllRepositoriesResponse(struct soap*, _mws__GetAllRepositoriesResponse **, const char*, const char*);
SOAP_FMAC3 _mws__GetAllRepositoriesResponse ** SOAP_FMAC4 soap_in_PointerTo_mws__GetAllRepositoriesResponse(struct soap*, const char*, _mws__GetAllRepositoriesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__GetAllRepositories
#define SOAP_TYPE_PointerTo_mws__GetAllRepositories (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__GetAllRepositories(struct soap*, _mws__GetAllRepositories *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__GetAllRepositories(struct soap*, _mws__GetAllRepositories *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__GetAllRepositories(struct soap*, const char *, int, _mws__GetAllRepositories *const*, const char *);
SOAP_FMAC3 _mws__GetAllRepositories ** SOAP_FMAC4 soap_get_PointerTo_mws__GetAllRepositories(struct soap*, _mws__GetAllRepositories **, const char*, const char*);
SOAP_FMAC3 _mws__GetAllRepositories ** SOAP_FMAC4 soap_in_PointerTo_mws__GetAllRepositories(struct soap*, const char*, _mws__GetAllRepositories **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__PickRepositoryResponse
#define SOAP_TYPE_PointerTo_mws__PickRepositoryResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__PickRepositoryResponse(struct soap*, _mws__PickRepositoryResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__PickRepositoryResponse(struct soap*, _mws__PickRepositoryResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__PickRepositoryResponse(struct soap*, const char *, int, _mws__PickRepositoryResponse *const*, const char *);
SOAP_FMAC3 _mws__PickRepositoryResponse ** SOAP_FMAC4 soap_get_PointerTo_mws__PickRepositoryResponse(struct soap*, _mws__PickRepositoryResponse **, const char*, const char*);
SOAP_FMAC3 _mws__PickRepositoryResponse ** SOAP_FMAC4 soap_in_PointerTo_mws__PickRepositoryResponse(struct soap*, const char*, _mws__PickRepositoryResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__PickRepository
#define SOAP_TYPE_PointerTo_mws__PickRepository (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__PickRepository(struct soap*, _mws__PickRepository *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__PickRepository(struct soap*, _mws__PickRepository *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__PickRepository(struct soap*, const char *, int, _mws__PickRepository *const*, const char *);
SOAP_FMAC3 _mws__PickRepository ** SOAP_FMAC4 soap_get_PointerTo_mws__PickRepository(struct soap*, _mws__PickRepository **, const char*, const char*);
SOAP_FMAC3 _mws__PickRepository ** SOAP_FMAC4 soap_in_PointerTo_mws__PickRepository(struct soap*, const char*, _mws__PickRepository **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__TryGetRepositoryInfoResponse
#define SOAP_TYPE_PointerTo_mws__TryGetRepositoryInfoResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__TryGetRepositoryInfoResponse(struct soap*, _mws__TryGetRepositoryInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__TryGetRepositoryInfoResponse(struct soap*, _mws__TryGetRepositoryInfoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__TryGetRepositoryInfoResponse(struct soap*, const char *, int, _mws__TryGetRepositoryInfoResponse *const*, const char *);
SOAP_FMAC3 _mws__TryGetRepositoryInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_mws__TryGetRepositoryInfoResponse(struct soap*, _mws__TryGetRepositoryInfoResponse **, const char*, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_mws__TryGetRepositoryInfoResponse(struct soap*, const char*, _mws__TryGetRepositoryInfoResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_mws__TryGetRepositoryInfo
#define SOAP_TYPE_PointerTo_mws__TryGetRepositoryInfo (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_mws__TryGetRepositoryInfo(struct soap*, _mws__TryGetRepositoryInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_mws__TryGetRepositoryInfo(struct soap*, _mws__TryGetRepositoryInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_mws__TryGetRepositoryInfo(struct soap*, const char *, int, _mws__TryGetRepositoryInfo *const*, const char *);
SOAP_FMAC3 _mws__TryGetRepositoryInfo ** SOAP_FMAC4 soap_get_PointerTo_mws__TryGetRepositoryInfo(struct soap*, _mws__TryGetRepositoryInfo **, const char*, const char*);
SOAP_FMAC3 _mws__TryGetRepositoryInfo ** SOAP_FMAC4 soap_in_PointerTo_mws__TryGetRepositoryInfo(struct soap*, const char*, _mws__TryGetRepositoryInfo **, const char*);

#ifndef SOAP_TYPE_PointerTomws__ArrayOfRepositoryInfo
#define SOAP_TYPE_PointerTomws__ArrayOfRepositoryInfo (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomws__ArrayOfRepositoryInfo(struct soap*, mws__ArrayOfRepositoryInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomws__ArrayOfRepositoryInfo(struct soap*, mws__ArrayOfRepositoryInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomws__ArrayOfRepositoryInfo(struct soap*, const char *, int, mws__ArrayOfRepositoryInfo *const*, const char *);
SOAP_FMAC3 mws__ArrayOfRepositoryInfo ** SOAP_FMAC4 soap_get_PointerTomws__ArrayOfRepositoryInfo(struct soap*, mws__ArrayOfRepositoryInfo **, const char*, const char*);
SOAP_FMAC3 mws__ArrayOfRepositoryInfo ** SOAP_FMAC4 soap_in_PointerTomws__ArrayOfRepositoryInfo(struct soap*, const char*, mws__ArrayOfRepositoryInfo **, const char*);

#ifndef SOAP_TYPE_PointerTomws__RepositoryInfo
#define SOAP_TYPE_PointerTomws__RepositoryInfo (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomws__RepositoryInfo(struct soap*, mws__RepositoryInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomws__RepositoryInfo(struct soap*, mws__RepositoryInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomws__RepositoryInfo(struct soap*, const char *, int, mws__RepositoryInfo *const*, const char *);
SOAP_FMAC3 mws__RepositoryInfo ** SOAP_FMAC4 soap_get_PointerTomws__RepositoryInfo(struct soap*, mws__RepositoryInfo **, const char*, const char*);
SOAP_FMAC3 mws__RepositoryInfo ** SOAP_FMAC4 soap_in_PointerTomws__RepositoryInfo(struct soap*, const char*, mws__RepositoryInfo **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTomws__RepositoryInfo
#define SOAP_TYPE_std__vectorTemplateOfPointerTomws__RepositoryInfo (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, const std::vector<mws__RepositoryInfo * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, std::vector<mws__RepositoryInfo * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, const char*, int, const std::vector<mws__RepositoryInfo * >*, const char*);
SOAP_FMAC3 std::vector<mws__RepositoryInfo * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, const char*, std::vector<mws__RepositoryInfo * >*, const char*);
SOAP_FMAC5 std::vector<mws__RepositoryInfo * > * SOAP_FMAC6 soap_new_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, std::vector<mws__RepositoryInfo * >*);
SOAP_FMAC3 std::vector<mws__RepositoryInfo * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTomws__RepositoryInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of repositoryH.h */
