/* repositoryStub.h
   Generated by gSOAP 2.8.8 from Repository.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef repositoryStub_H
#define repositoryStub_H
#include <vector>
#define SOAP_NAMESPACE_OF_mtrep	"http://miktex.org/2006/06/repository"
#define SOAP_NAMESPACE_OF_mtrep2	"http://miktex.org/2007/03/repository"
#define SOAP_NAMESPACE_OF_mtrep3	"http://miktex.org/2007/07/repository"
#define SOAP_NAMESPACE_OF_mtrep4	"http://miktex.org/2007/10/repository"
#define SOAP_NAMESPACE_OF_ns1	"http://miktex.org/2008/05/repository"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20808
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_mtrep__Integrities
#define SOAP_TYPE_mtrep__Integrities (41)
/* mtrep:Integrities */
enum mtrep__Integrities {mtrep__Integrities__Intact = 0, mtrep__Integrities__Corrupted = 1, mtrep__Integrities__Unknown = 2};
#endif

#ifndef SOAP_TYPE_mtrep__Levels
#define SOAP_TYPE_mtrep__Levels (42)
/* mtrep:Levels */
enum mtrep__Levels {mtrep__Levels__Essential = 0, mtrep__Levels__Basic = 1, mtrep__Levels__Advanced = 2, mtrep__Levels__Complete = 3};
#endif

#ifndef SOAP_TYPE_mtrep__RepositoryStatus
#define SOAP_TYPE_mtrep__RepositoryStatus (43)
/* mtrep:RepositoryStatus */
enum mtrep__RepositoryStatus {mtrep__RepositoryStatus__Online = 0, mtrep__RepositoryStatus__Offline = 1, mtrep__RepositoryStatus__Unknown = 2};
#endif

#ifndef SOAP_TYPE_mtrep3__Integrities
#define SOAP_TYPE_mtrep3__Integrities (44)
/* mtrep3:Integrities */
enum mtrep3__Integrities {mtrep3__Integrities__Intact = 0, mtrep3__Integrities__Corrupted = 1, mtrep3__Integrities__Unknown = 2};
#endif

#ifndef SOAP_TYPE_mtrep3__Levels
#define SOAP_TYPE_mtrep3__Levels (45)
/* mtrep3:Levels */
enum mtrep3__Levels {mtrep3__Levels__Essential = 0, mtrep3__Levels__Basic = 1, mtrep3__Levels__Advanced = 2, mtrep3__Levels__Complete = 3};
#endif

#ifndef SOAP_TYPE_mtrep3__RepositoryStatus
#define SOAP_TYPE_mtrep3__RepositoryStatus (46)
/* mtrep3:RepositoryStatus */
enum mtrep3__RepositoryStatus {mtrep3__RepositoryStatus__Online = 0, mtrep3__RepositoryStatus__Offline = 1, mtrep3__RepositoryStatus__Unknown = 2};
#endif

#ifndef SOAP_TYPE_mtrep4__Integrities
#define SOAP_TYPE_mtrep4__Integrities (47)
/* mtrep4:Integrities */
enum mtrep4__Integrities {mtrep4__Integrities__Intact = 0, mtrep4__Integrities__Corrupted = 1, mtrep4__Integrities__Unknown = 2};
#endif

#ifndef SOAP_TYPE_mtrep4__Levels
#define SOAP_TYPE_mtrep4__Levels (48)
/* mtrep4:Levels */
enum mtrep4__Levels {mtrep4__Levels__Essential = 0, mtrep4__Levels__Basic = 1, mtrep4__Levels__Advanced = 2, mtrep4__Levels__Complete = 3};
#endif

#ifndef SOAP_TYPE_mtrep4__RepositoryStatus
#define SOAP_TYPE_mtrep4__RepositoryStatus (49)
/* mtrep4:RepositoryStatus */
enum mtrep4__RepositoryStatus {mtrep4__RepositoryStatus__Online = 0, mtrep4__RepositoryStatus__Offline = 1, mtrep4__RepositoryStatus__Unknown = 2};
#endif

#ifndef SOAP_TYPE_ns1__Integrities
#define SOAP_TYPE_ns1__Integrities (50)
/* ns1:Integrities */
enum ns1__Integrities {ns1__Integrities__Intact = 0, ns1__Integrities__Corrupted = 1, ns1__Integrities__Unknown = 2};
#endif

#ifndef SOAP_TYPE_ns1__Levels
#define SOAP_TYPE_ns1__Levels (51)
/* ns1:Levels */
enum ns1__Levels {ns1__Levels__Essential = 0, ns1__Levels__Basic = 1, ns1__Levels__Advanced = 2, ns1__Levels__Complete = 3};
#endif

#ifndef SOAP_TYPE_ns1__RepositoryStatus
#define SOAP_TYPE_ns1__RepositoryStatus (52)
/* ns1:RepositoryStatus */
enum ns1__RepositoryStatus {ns1__RepositoryStatus__Online = 0, ns1__RepositoryStatus__Offline = 1, ns1__RepositoryStatus__Unknown = 2};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_mtrep__RepositoryInfo
#define SOAP_TYPE_mtrep__RepositoryInfo (8)
/* mtrep:RepositoryInfo */
class SOAP_CMAC mtrep__RepositoryInfo
{
public:
	std::string *Country;	/* optional element of type xsd:string */
	int Date;	/* required element of type xsd:int */
	int Delay;	/* required element of type xsd:int */
	std::string *Description;	/* optional element of type xsd:string */
	enum mtrep__Integrities Integrity;	/* required element of type mtrep:Integrities */
	enum mtrep__Levels Level;	/* required element of type mtrep:Levels */
	enum mtrep__RepositoryStatus Status;	/* required element of type mtrep:RepositoryStatus */
	std::string *Url;	/* optional element of type xsd:string */
	int Version;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_mtrep__RepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep__RepositoryInfo() { mtrep__RepositoryInfo::soap_default(NULL); }
	virtual ~mtrep__RepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE_mtrep__ArrayOfRepositoryInfo
#define SOAP_TYPE_mtrep__ArrayOfRepositoryInfo (9)
/* mtrep:ArrayOfRepositoryInfo */
class SOAP_CMAC mtrep__ArrayOfRepositoryInfo
{
public:
	std::vector<mtrep__RepositoryInfo * >RepositoryInfo;	/* optional element of type mtrep:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE_mtrep__ArrayOfRepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep__ArrayOfRepositoryInfo() { mtrep__ArrayOfRepositoryInfo::soap_default(NULL); }
	virtual ~mtrep__ArrayOfRepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__TryGetRepositoryInfo
#define SOAP_TYPE__mtrep__TryGetRepositoryInfo (10)
/* mtrep:TryGetRepositoryInfo */
class SOAP_CMAC _mtrep__TryGetRepositoryInfo
{
public:
	std::string *url;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE__mtrep__TryGetRepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__TryGetRepositoryInfo() { _mtrep__TryGetRepositoryInfo::soap_default(NULL); }
	virtual ~_mtrep__TryGetRepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__TryGetRepositoryInfoResponse
#define SOAP_TYPE__mtrep__TryGetRepositoryInfoResponse (11)
/* mtrep:TryGetRepositoryInfoResponse */
class SOAP_CMAC _mtrep__TryGetRepositoryInfoResponse
{
public:
	bool TryGetRepositoryInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	mtrep__RepositoryInfo *repositoryInfo;	/* optional element of type mtrep:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE__mtrep__TryGetRepositoryInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__TryGetRepositoryInfoResponse() { _mtrep__TryGetRepositoryInfoResponse::soap_default(NULL); }
	virtual ~_mtrep__TryGetRepositoryInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__PickRepository
#define SOAP_TYPE__mtrep__PickRepository (12)
/* mtrep:PickRepository */
class SOAP_CMAC _mtrep__PickRepository
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE__mtrep__PickRepository */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__PickRepository() { _mtrep__PickRepository::soap_default(NULL); }
	virtual ~_mtrep__PickRepository() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__PickRepositoryResponse
#define SOAP_TYPE__mtrep__PickRepositoryResponse (13)
/* mtrep:PickRepositoryResponse */
class SOAP_CMAC _mtrep__PickRepositoryResponse
{
public:
	mtrep__RepositoryInfo *PickRepositoryResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type mtrep:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE__mtrep__PickRepositoryResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__PickRepositoryResponse() { _mtrep__PickRepositoryResponse::soap_default(NULL); }
	virtual ~_mtrep__PickRepositoryResponse() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__GetAllRepositories
#define SOAP_TYPE__mtrep__GetAllRepositories (14)
/* mtrep:GetAllRepositories */
class SOAP_CMAC _mtrep__GetAllRepositories
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique id SOAP_TYPE__mtrep__GetAllRepositories */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__GetAllRepositories() { _mtrep__GetAllRepositories::soap_default(NULL); }
	virtual ~_mtrep__GetAllRepositories() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__GetAllRepositoriesResponse
#define SOAP_TYPE__mtrep__GetAllRepositoriesResponse (15)
/* mtrep:GetAllRepositoriesResponse */
class SOAP_CMAC _mtrep__GetAllRepositoriesResponse
{
public:
	mtrep__ArrayOfRepositoryInfo *GetAllRepositoriesResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type mtrep:ArrayOfRepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique id SOAP_TYPE__mtrep__GetAllRepositoriesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__GetAllRepositoriesResponse() { _mtrep__GetAllRepositoriesResponse::soap_default(NULL); }
	virtual ~_mtrep__GetAllRepositoriesResponse() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__GetRepositories
#define SOAP_TYPE__mtrep__GetRepositories (16)
/* mtrep:GetRepositories */
class SOAP_CMAC _mtrep__GetRepositories
{
public:
	bool onlyOnline;	/* required element of type xsd:boolean */
	bool noCorrupted;	/* required element of type xsd:boolean */
	int maxDelay;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique id SOAP_TYPE__mtrep__GetRepositories */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__GetRepositories() { _mtrep__GetRepositories::soap_default(NULL); }
	virtual ~_mtrep__GetRepositories() { }
};
#endif

#ifndef SOAP_TYPE__mtrep__GetRepositoriesResponse
#define SOAP_TYPE__mtrep__GetRepositoriesResponse (17)
/* mtrep:GetRepositoriesResponse */
class SOAP_CMAC _mtrep__GetRepositoriesResponse
{
public:
	mtrep__ArrayOfRepositoryInfo *GetRepositoriesResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type mtrep:ArrayOfRepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique id SOAP_TYPE__mtrep__GetRepositoriesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep__GetRepositoriesResponse() { _mtrep__GetRepositoriesResponse::soap_default(NULL); }
	virtual ~_mtrep__GetRepositoriesResponse() { }
};
#endif

#ifndef SOAP_TYPE__mtrep2__GetListCreationTime
#define SOAP_TYPE__mtrep2__GetListCreationTime (18)
/* mtrep2:GetListCreationTime */
class SOAP_CMAC _mtrep2__GetListCreationTime
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique id SOAP_TYPE__mtrep2__GetListCreationTime */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep2__GetListCreationTime() { _mtrep2__GetListCreationTime::soap_default(NULL); }
	virtual ~_mtrep2__GetListCreationTime() { }
};
#endif

#ifndef SOAP_TYPE__mtrep2__GetListCreationTimeResponse
#define SOAP_TYPE__mtrep2__GetListCreationTimeResponse (19)
/* mtrep2:GetListCreationTimeResponse */
class SOAP_CMAC _mtrep2__GetListCreationTimeResponse
{
public:
	int GetListCreationTimeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique id SOAP_TYPE__mtrep2__GetListCreationTimeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep2__GetListCreationTimeResponse() { _mtrep2__GetListCreationTimeResponse::soap_default(NULL); }
	virtual ~_mtrep2__GetListCreationTimeResponse() { }
};
#endif

#ifndef SOAP_TYPE_mtrep3__ClientInfo
#define SOAP_TYPE_mtrep3__ClientInfo (20)
/* mtrep3:ClientInfo */
class SOAP_CMAC mtrep3__ClientInfo
{
public:
	std::string *Name;	/* optional element of type xsd:string */
	std::string *Version;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 20; } /* = unique id SOAP_TYPE_mtrep3__ClientInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep3__ClientInfo() { mtrep3__ClientInfo::soap_default(NULL); }
	virtual ~mtrep3__ClientInfo() { }
};
#endif

#ifndef SOAP_TYPE_mtrep3__ArrayOfRepositoryInfo
#define SOAP_TYPE_mtrep3__ArrayOfRepositoryInfo (21)
/* mtrep3:ArrayOfRepositoryInfo */
class SOAP_CMAC mtrep3__ArrayOfRepositoryInfo
{
public:
	std::vector<class mtrep3__RepositoryInfo * >RepositoryInfo;	/* optional element of type mtrep3:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 21; } /* = unique id SOAP_TYPE_mtrep3__ArrayOfRepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep3__ArrayOfRepositoryInfo() { mtrep3__ArrayOfRepositoryInfo::soap_default(NULL); }
	virtual ~mtrep3__ArrayOfRepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE_mtrep3__RepositoryInfo
#define SOAP_TYPE_mtrep3__RepositoryInfo (22)
/* mtrep3:RepositoryInfo */
class SOAP_CMAC mtrep3__RepositoryInfo
{
public:
	std::string *Country;	/* optional element of type xsd:string */
	int Date;	/* required element of type xsd:int */
	int Delay;	/* required element of type xsd:int */
	std::string *Description;	/* optional element of type xsd:string */
	enum mtrep3__Integrities Integrity;	/* required element of type mtrep3:Integrities */
	enum mtrep3__Levels Level;	/* required element of type mtrep3:Levels */
	enum mtrep3__RepositoryStatus Status;	/* required element of type mtrep3:RepositoryStatus */
	std::string *Url;	/* optional element of type xsd:string */
	int Version;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 22; } /* = unique id SOAP_TYPE_mtrep3__RepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep3__RepositoryInfo() { mtrep3__RepositoryInfo::soap_default(NULL); }
	virtual ~mtrep3__RepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__GetRepositories2
#define SOAP_TYPE__mtrep3__GetRepositories2 (23)
/* mtrep3:GetRepositories2 */
class SOAP_CMAC _mtrep3__GetRepositories2
{
public:
	mtrep3__ClientInfo *clientInfo;	/* optional element of type mtrep3:ClientInfo */
	bool onlyOnline;	/* required element of type xsd:boolean */
	bool noCorrupted;	/* required element of type xsd:boolean */
	int maxDelay;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 23; } /* = unique id SOAP_TYPE__mtrep3__GetRepositories2 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__GetRepositories2() { _mtrep3__GetRepositories2::soap_default(NULL); }
	virtual ~_mtrep3__GetRepositories2() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__GetRepositories2Response
#define SOAP_TYPE__mtrep3__GetRepositories2Response (24)
/* mtrep3:GetRepositories2Response */
class SOAP_CMAC _mtrep3__GetRepositories2Response
{
public:
	mtrep3__ArrayOfRepositoryInfo *GetRepositories2Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type mtrep3:ArrayOfRepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 24; } /* = unique id SOAP_TYPE__mtrep3__GetRepositories2Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__GetRepositories2Response() { _mtrep3__GetRepositories2Response::soap_default(NULL); }
	virtual ~_mtrep3__GetRepositories2Response() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__PickRepository2
#define SOAP_TYPE__mtrep3__PickRepository2 (25)
/* mtrep3:PickRepository2 */
class SOAP_CMAC _mtrep3__PickRepository2
{
public:
	mtrep3__ClientInfo *clientInfo;	/* optional element of type mtrep3:ClientInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 25; } /* = unique id SOAP_TYPE__mtrep3__PickRepository2 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__PickRepository2() { _mtrep3__PickRepository2::soap_default(NULL); }
	virtual ~_mtrep3__PickRepository2() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__PickRepository2Response
#define SOAP_TYPE__mtrep3__PickRepository2Response (26)
/* mtrep3:PickRepository2Response */
class SOAP_CMAC _mtrep3__PickRepository2Response
{
public:
	mtrep3__RepositoryInfo *PickRepository2Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type mtrep3:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique id SOAP_TYPE__mtrep3__PickRepository2Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__PickRepository2Response() { _mtrep3__PickRepository2Response::soap_default(NULL); }
	virtual ~_mtrep3__PickRepository2Response() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__TryGetRepositoryInfo2
#define SOAP_TYPE__mtrep3__TryGetRepositoryInfo2 (27)
/* mtrep3:TryGetRepositoryInfo2 */
class SOAP_CMAC _mtrep3__TryGetRepositoryInfo2
{
public:
	mtrep3__ClientInfo *clientInfo;	/* optional element of type mtrep3:ClientInfo */
	std::string *url;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 27; } /* = unique id SOAP_TYPE__mtrep3__TryGetRepositoryInfo2 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__TryGetRepositoryInfo2() { _mtrep3__TryGetRepositoryInfo2::soap_default(NULL); }
	virtual ~_mtrep3__TryGetRepositoryInfo2() { }
};
#endif

#ifndef SOAP_TYPE__mtrep3__TryGetRepositoryInfo2Response
#define SOAP_TYPE__mtrep3__TryGetRepositoryInfo2Response (28)
/* mtrep3:TryGetRepositoryInfo2Response */
class SOAP_CMAC _mtrep3__TryGetRepositoryInfo2Response
{
public:
	bool TryGetRepositoryInfo2Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	mtrep3__RepositoryInfo *repositoryInfo;	/* optional element of type mtrep3:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 28; } /* = unique id SOAP_TYPE__mtrep3__TryGetRepositoryInfo2Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep3__TryGetRepositoryInfo2Response() { _mtrep3__TryGetRepositoryInfo2Response::soap_default(NULL); }
	virtual ~_mtrep3__TryGetRepositoryInfo2Response() { }
};
#endif

#ifndef SOAP_TYPE_mtrep4__ClientInfo
#define SOAP_TYPE_mtrep4__ClientInfo (29)
/* mtrep4:ClientInfo */
class SOAP_CMAC mtrep4__ClientInfo
{
public:
	std::string *Name;	/* optional element of type xsd:string */
	std::string *Version;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 29; } /* = unique id SOAP_TYPE_mtrep4__ClientInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep4__ClientInfo() { mtrep4__ClientInfo::soap_default(NULL); }
	virtual ~mtrep4__ClientInfo() { }
};
#endif

#ifndef SOAP_TYPE_mtrep4__RepositoryInfo
#define SOAP_TYPE_mtrep4__RepositoryInfo (30)
/* mtrep4:RepositoryInfo */
class SOAP_CMAC mtrep4__RepositoryInfo
{
public:
	std::string *Country;	/* optional element of type xsd:string */
	int Date;	/* required element of type xsd:int */
	int Delay;	/* required element of type xsd:int */
	std::string *Description;	/* optional element of type xsd:string */
	enum mtrep4__Integrities Integrity;	/* required element of type mtrep4:Integrities */
	enum mtrep4__Levels Level;	/* required element of type mtrep4:Levels */
	enum mtrep4__RepositoryStatus Status;	/* required element of type mtrep4:RepositoryStatus */
	std::string *Url;	/* optional element of type xsd:string */
	int Version;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 30; } /* = unique id SOAP_TYPE_mtrep4__RepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         mtrep4__RepositoryInfo() { mtrep4__RepositoryInfo::soap_default(NULL); }
	virtual ~mtrep4__RepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE__mtrep4__VerifyRepository
#define SOAP_TYPE__mtrep4__VerifyRepository (31)
/* mtrep4:VerifyRepository */
class SOAP_CMAC _mtrep4__VerifyRepository
{
public:
	mtrep4__ClientInfo *clientInfo;	/* optional element of type mtrep4:ClientInfo */
	std::string *url;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 31; } /* = unique id SOAP_TYPE__mtrep4__VerifyRepository */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep4__VerifyRepository() { _mtrep4__VerifyRepository::soap_default(NULL); }
	virtual ~_mtrep4__VerifyRepository() { }
};
#endif

#ifndef SOAP_TYPE__mtrep4__VerifyRepositoryResponse
#define SOAP_TYPE__mtrep4__VerifyRepositoryResponse (32)
/* mtrep4:VerifyRepositoryResponse */
class SOAP_CMAC _mtrep4__VerifyRepositoryResponse
{
public:
	bool VerifyRepositoryResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	mtrep4__RepositoryInfo *repositoryInfo;	/* optional element of type mtrep4:RepositoryInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 32; } /* = unique id SOAP_TYPE__mtrep4__VerifyRepositoryResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _mtrep4__VerifyRepositoryResponse() { _mtrep4__VerifyRepositoryResponse::soap_default(NULL); }
	virtual ~_mtrep4__VerifyRepositoryResponse() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ClientInfo
#define SOAP_TYPE_ns1__ClientInfo (33)
/* ns1:ClientInfo */
class SOAP_CMAC ns1__ClientInfo
{
public:
	std::string *Name;	/* optional element of type xsd:string */
	std::string *Version;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 33; } /* = unique id SOAP_TYPE_ns1__ClientInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ClientInfo() { ns1__ClientInfo::soap_default(NULL); }
	virtual ~ns1__ClientInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfRepositoryInfo2
#define SOAP_TYPE_ns1__ArrayOfRepositoryInfo2 (34)
/* ns1:ArrayOfRepositoryInfo2 */
class SOAP_CMAC ns1__ArrayOfRepositoryInfo2
{
public:
	std::vector<class ns1__RepositoryInfo2 * >RepositoryInfo2;	/* optional element of type ns1:RepositoryInfo2 */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 34; } /* = unique id SOAP_TYPE_ns1__ArrayOfRepositoryInfo2 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ArrayOfRepositoryInfo2() { ns1__ArrayOfRepositoryInfo2::soap_default(NULL); }
	virtual ~ns1__ArrayOfRepositoryInfo2() { }
};
#endif

#ifndef SOAP_TYPE_ns1__RepositoryInfo
#define SOAP_TYPE_ns1__RepositoryInfo (36)
/* ns1:RepositoryInfo */
class SOAP_CMAC ns1__RepositoryInfo
{
public:
	std::string *Country;	/* optional element of type xsd:string */
	int Date;	/* required element of type xsd:int */
	int Delay;	/* required element of type xsd:int */
	std::string *Description;	/* optional element of type xsd:string */
	enum ns1__Integrities Integrity;	/* required element of type ns1:Integrities */
	enum ns1__Levels Level;	/* required element of type ns1:Levels */
	enum ns1__RepositoryStatus Status;	/* required element of type ns1:RepositoryStatus */
	std::string *Url;	/* optional element of type xsd:string */
	int Version;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 36; } /* = unique id SOAP_TYPE_ns1__RepositoryInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__RepositoryInfo() { ns1__RepositoryInfo::soap_default(NULL); }
	virtual ~ns1__RepositoryInfo() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetRepositories3
#define SOAP_TYPE__ns1__GetRepositories3 (37)
/* ns1:GetRepositories3 */
class SOAP_CMAC _ns1__GetRepositories3
{
public:
	ns1__ClientInfo *clientInfo;	/* optional element of type ns1:ClientInfo */
	bool onlyOnline;	/* required element of type xsd:boolean */
	bool noCorrupted;	/* required element of type xsd:boolean */
	bool httpOnly;	/* required element of type xsd:boolean */
	bool excludeHidden;	/* required element of type xsd:boolean */
	int maxDelay;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 37; } /* = unique id SOAP_TYPE__ns1__GetRepositories3 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetRepositories3() { _ns1__GetRepositories3::soap_default(NULL); }
	virtual ~_ns1__GetRepositories3() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetRepositories3Response
#define SOAP_TYPE__ns1__GetRepositories3Response (38)
/* ns1:GetRepositories3Response */
class SOAP_CMAC _ns1__GetRepositories3Response
{
public:
	ns1__ArrayOfRepositoryInfo2 *GetRepositories3Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfRepositoryInfo2 */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 38; } /* = unique id SOAP_TYPE__ns1__GetRepositories3Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetRepositories3Response() { _ns1__GetRepositories3Response::soap_default(NULL); }
	virtual ~_ns1__GetRepositories3Response() { }
};
#endif

#ifndef SOAP_TYPE__ns1__PickRepository3
#define SOAP_TYPE__ns1__PickRepository3 (39)
/* ns1:PickRepository3 */
class SOAP_CMAC _ns1__PickRepository3
{
public:
	ns1__ClientInfo *clientInfo;	/* optional element of type ns1:ClientInfo */
	bool favorHttp;	/* required element of type xsd:boolean */
	bool nearest;	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 39; } /* = unique id SOAP_TYPE__ns1__PickRepository3 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__PickRepository3() { _ns1__PickRepository3::soap_default(NULL); }
	virtual ~_ns1__PickRepository3() { }
};
#endif

#ifndef SOAP_TYPE__ns1__PickRepository3Response
#define SOAP_TYPE__ns1__PickRepository3Response (40)
/* ns1:PickRepository3Response */
class SOAP_CMAC _ns1__PickRepository3Response
{
public:
	ns1__RepositoryInfo2 *PickRepository3Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:RepositoryInfo2 */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 40; } /* = unique id SOAP_TYPE__ns1__PickRepository3Response */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__PickRepository3Response() { _ns1__PickRepository3Response::soap_default(NULL); }
	virtual ~_ns1__PickRepository3Response() { }
};
#endif

#ifndef SOAP_TYPE_ns1__RepositoryInfo2
#define SOAP_TYPE_ns1__RepositoryInfo2 (35)
/* ns1:RepositoryInfo2 */
class SOAP_CMAC ns1__RepositoryInfo2 : public ns1__RepositoryInfo
{
public:
	std::string *CountryCode;	/* optional element of type xsd:string */
	std::string *City;	/* optional element of type xsd:string */
	double Latitude;	/* required element of type xsd:double */
	double Longitude;	/* required element of type xsd:double */
public:
	virtual int soap_type() const { return 35; } /* = unique id SOAP_TYPE_ns1__RepositoryInfo2 */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__RepositoryInfo2() { ns1__RepositoryInfo2::soap_default(NULL); }
	virtual ~ns1__RepositoryInfo2() { }
};
#endif

#ifndef SOAP_TYPE___ns2__TryGetRepositoryInfo
#define SOAP_TYPE___ns2__TryGetRepositoryInfo (74)
/* Operation wrapper: */
struct __ns2__TryGetRepositoryInfo
{
public:
	_mtrep__TryGetRepositoryInfo *mtrep__TryGetRepositoryInfo;	/* optional element of type mtrep:TryGetRepositoryInfo */
};
#endif

#ifndef SOAP_TYPE___ns2__PickRepository
#define SOAP_TYPE___ns2__PickRepository (78)
/* Operation wrapper: */
struct __ns2__PickRepository
{
public:
	_mtrep__PickRepository *mtrep__PickRepository;	/* optional element of type mtrep:PickRepository */
};
#endif

#ifndef SOAP_TYPE___ns2__GetAllRepositories
#define SOAP_TYPE___ns2__GetAllRepositories (82)
/* Operation wrapper: */
struct __ns2__GetAllRepositories
{
public:
	_mtrep__GetAllRepositories *mtrep__GetAllRepositories;	/* optional element of type mtrep:GetAllRepositories */
};
#endif

#ifndef SOAP_TYPE___ns2__GetRepositories
#define SOAP_TYPE___ns2__GetRepositories (86)
/* Operation wrapper: */
struct __ns2__GetRepositories
{
public:
	_mtrep__GetRepositories *mtrep__GetRepositories;	/* optional element of type mtrep:GetRepositories */
};
#endif

#ifndef SOAP_TYPE___ns2__GetListCreationTime
#define SOAP_TYPE___ns2__GetListCreationTime (90)
/* Operation wrapper: */
struct __ns2__GetListCreationTime
{
public:
	_mtrep2__GetListCreationTime *mtrep2__GetListCreationTime;	/* optional element of type mtrep2:GetListCreationTime */
};
#endif

#ifndef SOAP_TYPE___ns2__GetRepositories2
#define SOAP_TYPE___ns2__GetRepositories2 (94)
/* Operation wrapper: */
struct __ns2__GetRepositories2
{
public:
	_mtrep3__GetRepositories2 *mtrep3__GetRepositories2;	/* optional element of type mtrep3:GetRepositories2 */
};
#endif

#ifndef SOAP_TYPE___ns2__PickRepository2
#define SOAP_TYPE___ns2__PickRepository2 (98)
/* Operation wrapper: */
struct __ns2__PickRepository2
{
public:
	_mtrep3__PickRepository2 *mtrep3__PickRepository2;	/* optional element of type mtrep3:PickRepository2 */
};
#endif

#ifndef SOAP_TYPE___ns2__TryGetRepositoryInfo2
#define SOAP_TYPE___ns2__TryGetRepositoryInfo2 (102)
/* Operation wrapper: */
struct __ns2__TryGetRepositoryInfo2
{
public:
	_mtrep3__TryGetRepositoryInfo2 *mtrep3__TryGetRepositoryInfo2;	/* optional element of type mtrep3:TryGetRepositoryInfo2 */
};
#endif

#ifndef SOAP_TYPE___ns2__VerifyRepository
#define SOAP_TYPE___ns2__VerifyRepository (106)
/* Operation wrapper: */
struct __ns2__VerifyRepository
{
public:
	_mtrep4__VerifyRepository *mtrep4__VerifyRepository;	/* optional element of type mtrep4:VerifyRepository */
};
#endif

#ifndef SOAP_TYPE___ns2__GetRepositories3
#define SOAP_TYPE___ns2__GetRepositories3 (110)
/* Operation wrapper: */
struct __ns2__GetRepositories3
{
public:
	_ns1__GetRepositories3 *ns1__GetRepositories3;	/* optional element of type ns1:GetRepositories3 */
};
#endif

#ifndef SOAP_TYPE___ns2__PickRepository3
#define SOAP_TYPE___ns2__PickRepository3 (114)
/* Operation wrapper: */
struct __ns2__PickRepository3
{
public:
	_ns1__PickRepository3 *ns1__PickRepository3;	/* optional element of type ns1:PickRepository3 */
};
#endif

#ifndef SOAP_TYPE___ns3__TryGetRepositoryInfo
#define SOAP_TYPE___ns3__TryGetRepositoryInfo (116)
/* Operation wrapper: */
struct __ns3__TryGetRepositoryInfo
{
public:
	_mtrep__TryGetRepositoryInfo *mtrep__TryGetRepositoryInfo;	/* optional element of type mtrep:TryGetRepositoryInfo */
};
#endif

#ifndef SOAP_TYPE___ns3__PickRepository
#define SOAP_TYPE___ns3__PickRepository (118)
/* Operation wrapper: */
struct __ns3__PickRepository
{
public:
	_mtrep__PickRepository *mtrep__PickRepository;	/* optional element of type mtrep:PickRepository */
};
#endif

#ifndef SOAP_TYPE___ns3__GetAllRepositories
#define SOAP_TYPE___ns3__GetAllRepositories (120)
/* Operation wrapper: */
struct __ns3__GetAllRepositories
{
public:
	_mtrep__GetAllRepositories *mtrep__GetAllRepositories;	/* optional element of type mtrep:GetAllRepositories */
};
#endif

#ifndef SOAP_TYPE___ns3__GetRepositories
#define SOAP_TYPE___ns3__GetRepositories (122)
/* Operation wrapper: */
struct __ns3__GetRepositories
{
public:
	_mtrep__GetRepositories *mtrep__GetRepositories;	/* optional element of type mtrep:GetRepositories */
};
#endif

#ifndef SOAP_TYPE___ns3__GetListCreationTime
#define SOAP_TYPE___ns3__GetListCreationTime (124)
/* Operation wrapper: */
struct __ns3__GetListCreationTime
{
public:
	_mtrep2__GetListCreationTime *mtrep2__GetListCreationTime;	/* optional element of type mtrep2:GetListCreationTime */
};
#endif

#ifndef SOAP_TYPE___ns3__GetRepositories2
#define SOAP_TYPE___ns3__GetRepositories2 (126)
/* Operation wrapper: */
struct __ns3__GetRepositories2
{
public:
	_mtrep3__GetRepositories2 *mtrep3__GetRepositories2;	/* optional element of type mtrep3:GetRepositories2 */
};
#endif

#ifndef SOAP_TYPE___ns3__PickRepository2
#define SOAP_TYPE___ns3__PickRepository2 (128)
/* Operation wrapper: */
struct __ns3__PickRepository2
{
public:
	_mtrep3__PickRepository2 *mtrep3__PickRepository2;	/* optional element of type mtrep3:PickRepository2 */
};
#endif

#ifndef SOAP_TYPE___ns3__TryGetRepositoryInfo2
#define SOAP_TYPE___ns3__TryGetRepositoryInfo2 (130)
/* Operation wrapper: */
struct __ns3__TryGetRepositoryInfo2
{
public:
	_mtrep3__TryGetRepositoryInfo2 *mtrep3__TryGetRepositoryInfo2;	/* optional element of type mtrep3:TryGetRepositoryInfo2 */
};
#endif

#ifndef SOAP_TYPE___ns3__VerifyRepository
#define SOAP_TYPE___ns3__VerifyRepository (132)
/* Operation wrapper: */
struct __ns3__VerifyRepository
{
public:
	_mtrep4__VerifyRepository *mtrep4__VerifyRepository;	/* optional element of type mtrep4:VerifyRepository */
};
#endif

#ifndef SOAP_TYPE___ns3__GetRepositories3
#define SOAP_TYPE___ns3__GetRepositories3 (134)
/* Operation wrapper: */
struct __ns3__GetRepositories3
{
public:
	_ns1__GetRepositories3 *ns1__GetRepositories3;	/* optional element of type ns1:GetRepositories3 */
};
#endif

#ifndef SOAP_TYPE___ns3__PickRepository3
#define SOAP_TYPE___ns3__PickRepository3 (136)
/* Operation wrapper: */
struct __ns3__PickRepository3
{
public:
	_ns1__PickRepository3 *ns1__PickRepository3;	/* optional element of type ns1:PickRepository3 */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (137)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (138)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (140)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (143)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (144)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of repositoryStub.h */
