/* repositoryRepositorySoapProxy.h
   Generated by gSOAP 2.7.17 from C:/work3/miktex-2.9/Libraries/MiKTeX/WebServiceClients/Repository/Repository.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef repositoryRepositorySoapProxy_H
#define repositoryRepositorySoapProxy_H
#include "repositoryH.h"

class SOAP_CMAC RepositorySoapProxy : public soap
{ public:
	/// Endpoint URL of service 'RepositorySoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	RepositorySoapProxy();
	/// Constructor with copy of another engine state
	RepositorySoapProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	RepositorySoapProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	RepositorySoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~RepositorySoapProxy();
	/// Initializer used by constructors
	virtual	void RepositorySoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'TryGetRepositoryInfo' (returns error code or SOAP_OK)
	virtual	int TryGetRepositoryInfo(_mtrep__TryGetRepositoryInfo *mtrep__TryGetRepositoryInfo, _mtrep__TryGetRepositoryInfoResponse *mtrep__TryGetRepositoryInfoResponse);

	/// Web service operation 'PickRepository' (returns error code or SOAP_OK)
	virtual	int PickRepository(_mtrep__PickRepository *mtrep__PickRepository, _mtrep__PickRepositoryResponse *mtrep__PickRepositoryResponse);

	/// Web service operation 'GetAllRepositories' (returns error code or SOAP_OK)
	virtual	int GetAllRepositories(_mtrep__GetAllRepositories *mtrep__GetAllRepositories, _mtrep__GetAllRepositoriesResponse *mtrep__GetAllRepositoriesResponse);

	/// Web service operation 'GetRepositories' (returns error code or SOAP_OK)
	virtual	int GetRepositories(_mtrep__GetRepositories *mtrep__GetRepositories, _mtrep__GetRepositoriesResponse *mtrep__GetRepositoriesResponse);

	/// Web service operation 'GetListCreationTime' (returns error code or SOAP_OK)
	virtual	int GetListCreationTime(_mtrep2__GetListCreationTime *mtrep2__GetListCreationTime, _mtrep2__GetListCreationTimeResponse *mtrep2__GetListCreationTimeResponse);

	/// Web service operation 'GetRepositories2' (returns error code or SOAP_OK)
	virtual	int GetRepositories2(_mtrep3__GetRepositories2 *mtrep3__GetRepositories2, _mtrep3__GetRepositories2Response *mtrep3__GetRepositories2Response);

	/// Web service operation 'PickRepository2' (returns error code or SOAP_OK)
	virtual	int PickRepository2(_mtrep3__PickRepository2 *mtrep3__PickRepository2, _mtrep3__PickRepository2Response *mtrep3__PickRepository2Response);

	/// Web service operation 'TryGetRepositoryInfo2' (returns error code or SOAP_OK)
	virtual	int TryGetRepositoryInfo2(_mtrep3__TryGetRepositoryInfo2 *mtrep3__TryGetRepositoryInfo2, _mtrep3__TryGetRepositoryInfo2Response *mtrep3__TryGetRepositoryInfo2Response);

	/// Web service operation 'VerifyRepository' (returns error code or SOAP_OK)
	virtual	int VerifyRepository(_mtrep4__VerifyRepository *mtrep4__VerifyRepository, _mtrep4__VerifyRepositoryResponse *mtrep4__VerifyRepositoryResponse);

	/// Web service operation 'TryGetRepositoryInfo' (returns error code or SOAP_OK)
	virtual	int TryGetRepositoryInfo_(_mtrep__TryGetRepositoryInfo *mtrep__TryGetRepositoryInfo, _mtrep__TryGetRepositoryInfoResponse *mtrep__TryGetRepositoryInfoResponse);

	/// Web service operation 'PickRepository' (returns error code or SOAP_OK)
	virtual	int PickRepository_(_mtrep__PickRepository *mtrep__PickRepository, _mtrep__PickRepositoryResponse *mtrep__PickRepositoryResponse);

	/// Web service operation 'GetAllRepositories' (returns error code or SOAP_OK)
	virtual	int GetAllRepositories_(_mtrep__GetAllRepositories *mtrep__GetAllRepositories, _mtrep__GetAllRepositoriesResponse *mtrep__GetAllRepositoriesResponse);

	/// Web service operation 'GetRepositories' (returns error code or SOAP_OK)
	virtual	int GetRepositories_(_mtrep__GetRepositories *mtrep__GetRepositories, _mtrep__GetRepositoriesResponse *mtrep__GetRepositoriesResponse);

	/// Web service operation 'GetListCreationTime' (returns error code or SOAP_OK)
	virtual	int GetListCreationTime_(_mtrep2__GetListCreationTime *mtrep2__GetListCreationTime, _mtrep2__GetListCreationTimeResponse *mtrep2__GetListCreationTimeResponse);

	/// Web service operation 'GetRepositories2' (returns error code or SOAP_OK)
	virtual	int GetRepositories2_(_mtrep3__GetRepositories2 *mtrep3__GetRepositories2, _mtrep3__GetRepositories2Response *mtrep3__GetRepositories2Response);

	/// Web service operation 'PickRepository2' (returns error code or SOAP_OK)
	virtual	int PickRepository2_(_mtrep3__PickRepository2 *mtrep3__PickRepository2, _mtrep3__PickRepository2Response *mtrep3__PickRepository2Response);

	/// Web service operation 'TryGetRepositoryInfo2' (returns error code or SOAP_OK)
	virtual	int TryGetRepositoryInfo2_(_mtrep3__TryGetRepositoryInfo2 *mtrep3__TryGetRepositoryInfo2, _mtrep3__TryGetRepositoryInfo2Response *mtrep3__TryGetRepositoryInfo2Response);

	/// Web service operation 'VerifyRepository' (returns error code or SOAP_OK)
	virtual	int VerifyRepository_(_mtrep4__VerifyRepository *mtrep4__VerifyRepository, _mtrep4__VerifyRepositoryResponse *mtrep4__VerifyRepositoryResponse);
};
#endif
